export const data = [
    {id: 1, name: 'Shoaziz', status: 'st'},
    {id: 2, name: 'Sobirjon', status: 'unm'},
    {id: 3, name: 'Azizbek', status: 'em'},
    {id: 4, name: 'Abdulaziz', status: 'bs'},
    {id: 5, name: 'Hojiakbar', status: 'unm'},
    {id: 6, name: 'Abdurahmon', status: 'bs'},
    {id: 7, name: 'Sardorbek', status: 'st'},
    {id: 8, name: 'Kamoliddin', status: 'bs'},
    {id: 9, name: 'Azimxon', status: 'st'},
    {id: 10, name: 'Ibrohim', status: 'em'},
    {id: 11, name: 'Sayfiddin', status: 'em'},
    {id: 12, name: 'Odina', status: 'em'},
    {id: 13, name: 'Ruqiya', status: 'em'},
]